services:
  - type: web
    name: CarnetDigitalUEB
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PGSQL_HOST
        value: "dpg-d2jl52a4d50c7386ben0-a.oregon-postgres.render.com"
      - key: PGSQL_DB
        value: "alumnosueb_9r34"
      - key: PGSQL_USER
        value: "root"
      - key: PGSQL_PASSWORD
        value: "mmxDA4jxOCxG53IhsdhFVxAtYzcNofwj"
 
