services:
  - type: web
    name: CarnetDigitalUEB
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PGSQL_HOST
        value: "dpg-d6gfcmua2pns73ft293g-a.oregon-postgres.render.com"
      - key: PGSQL_DB
        value: "alumnosueb_t1qc"
      - key: PGSQL_USER
        value: "root"
      - key: PGSQL_PASSWORD
        value: "OzKHrB6Ovi0o9YljuP2V7rzAmtizby7p"
 
